//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace g25_cg_csj_shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("g25_cg_csj_shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // S = Specification of algebra. (G25.spec)
        ///// FT = floating point type (G25.FloatType)
        ///// gmvName = name of GMV class
        ///// fabsFunc = name of floating point absolute function
        ///${CODEBLOCK GMVlargestCoordinate}
        ///&lt;%if (S.m_outputLanguage == G25.OUTPUT_LANGUAGE.CSHARP) {%&gt;
        ///	/// &lt;summary&gt;returns the absolute largest coordinate.&lt;/summary&gt;
        ///&lt;%} else {%&gt;
        ///	/** returns the absolute largest coordinate.*/
        ///&lt;%}%&gt;
        ///	public &lt;%FT.type%&gt; &lt;%G25.CG.CSJ.Util.GetFunctionName(S, &quot;largestCoordinate&quot;)%&gt;() {
        ///		&lt;%FT.type%&gt; max [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cg_csj_shared_templates {
            get {
                return ResourceManager.GetString("cg_csj_shared_templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string cg_csj_shared_test_templates {
            get {
                return ResourceManager.GetString("cg_csj_shared_test_templates", resourceCulture);
            }
        }
    }
}
